# Site settings
title: "Mohammed Ibrahim"
email:
description: "Mohammed Ibrahim's Personal Site"
baseurl:
url:
title_description: "Student at the University of Guelph working towards my Computer Science co-op degree with a minor in statistics. Graduating April 2022."
title_image: "images/flutter.jpg"
google_analytics: "UA-67857103-1"
disqus_account:
github_repository: http://mnayer.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username:
github_username: nayerm
linkedin_link: https://www.linkedin.com/in/mnayer/
google_plus_link:
stackoverflow_link:

# Footer
footer_left: "Friendship is Magic <i class=\"fa fa-heart\"></i></a>"
footer_right: "&lt;/&gt; <i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
